function(kpt_generate_i18n I18N_SOURCE_DIR OUTPUT_FILE)
  set(languages "en" "zh-CN")
  set(content "// Auto-generated by CMake i18n.cmake. Do not edit.\n")
  set(content "${content}#include \"i18n/i18n.hpp\"\n")
  set(content "${content}#include <array>\n")
  set(content "${content}#include <string_view>\n")
  set(content "${content}#include <unordered_map>\n\n")
  set(content "${content}namespace kpt::i18n::detail {\n\n")

  foreach(lang ${languages})
    file(READ "${I18N_SOURCE_DIR}/${lang}.json" json_content)
    string(REPLACE "-" "_" lang_var "${lang}")
    string(TOLOWER "${lang_var}" lang_var)

    set(content "${content}const std::unordered_map<std::string_view, std::string_view>& translations_${lang_var}() {\n")
    set(content "${content}  static const std::unordered_map<std::string_view, std::string_view> map = {\n")

    string(JSON num_keys LENGTH "${json_content}")
    if(num_keys GREATER 0)
      math(EXPR last_index "${num_keys} - 1")
      foreach(i RANGE ${last_index})
        string(JSON key MEMBER "${json_content}" ${i})
        string(JSON value GET "${json_content}" "${key}")

        string(REPLACE "\\" "\\\\" value "${value}")
        string(REPLACE "\"" "\\\"" value "${value}")
        string(REPLACE "\n" "\\n" value "${value}")

        set(content "${content}    {\"${key}\", \"${value}\"},\n")
      endforeach()
    endif()

    set(content "${content}  };\n  return map;\n}\n\n")
  endforeach()

  set(content "${content}} // namespace kpt::i18n::detail\n")
  file(WRITE "${OUTPUT_FILE}" "${content}")
endfunction()
